version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - rm -rf /var/app/current/node_modules
      - npm install
  build:
    commands:
      - echo Build Started

artifacts:
  files:
    # - yarn.lock
    - src/bin/www.js
    - src/app.js
    - src/routes/*
    - src/views/*
    - src/utils/*
    - src/libs/*
    - public/*
    - public/**/*
    - node_modules/**/*
    - package.json
    # - "build/**/*"
    # - ".platform/**/*" # AWS Elastic Beanstalk configuration files
    # - ".ebextensions/**/*" # AWS Elastic Beanstalk configuration files
  discard-paths: no
