version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - cd server && npm install
  build:
    commands:
      - npm run build
      - echo Build Started

artifacts:
  files:
    # - yarn.lock
    - src/*
    - public/*
    - server/*
    - server/**/*
    - node_modules/**/*
    - package.json
    - build/*
    - build/**/*
    # - ".platform/**/*" # AWS Elastic Beanstalk configuration files
    # - ".ebextensions/**/*" # AWS Elastic Beanstalk configuration files
  discard-paths: no
