branch-defaults:
  DEVUVA-34-Setup-Research-CodeBuild:
    environment: Jaal-WebApp
  DEVUVA-69-Add-ORM-to-communicate-to-AWS-RDS-DB:
    environment: test-env-con-2
  default:
    environment: Jaal-WebApp
    group_suffix: null
environment-defaults:
  Jaal-Web-App:
    branch: null
    repository: null
  Jaal-WebApp:
    branch: null
    repository: null
  test-env-con-2:
    branch: null
    repository: null
global:
  application_name: JaalSampleApp
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
