branch-defaults:
  default:
    environment: jaal-sample-app-dss
    group_suffix: null
global:
  application_name: JaalSampleApp
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
